-- ============================================================================
-- Boss Timers: encounter data
-- Generated; regenerate rather than edit by hand.
--
-- Per encounter id:
--   instance, boss   English names; raid = true for raid bosses
--   abilities        [event id] = { spell, kind, severity, cast, channel, flags, label }
--                    kind: tank, healer, targeted, mechanic, special, other.
--                    The ability's name comes from the game by spell id.
--   rules            how a timeline event is recognised: its duration in seconds
--                    (time) is matched to an event id. sync rules belong to a
--                    batch of events added together; group + order rotate
--                    abilities that share one duration.
--   machine          phases, for bosses whose durations change with the phase:
--                    each phase has its own rules and how it is entered.
--   health           health percentages where the fight changes.
-- ============================================================================

local addonName, OxedHub = ...

OxedHub.BossData = {
    encounters = {
        [2124] = {
            instance = "Temple of Sethraliss",
            boss = "Adderis and Aspix",
            raid = false,
            mapID = 1877,
            order = 1,
            journalID = 2142,
            portrait = 2176710,
            abilities = {
                [689] = { spell = 1288235, kind = "healer", severity = 2, cast = 4, flags = 0 },
                [690] = { spell = 1288428, kind = "healer", severity = 1, cast = 3, flags = 0, label = "TANK HIT" },
                [691] = { spell = 1288864, kind = "targeted", severity = 1, cast = 3, flags = 0 },
                [692] = { spell = 1289062, kind = "healer", severity = 1, cast = 3.5, flags = 0 },
                [713] = { spell = 1288864, kind = "targeted", severity = 1, cast = 2, flags = 0 },
                [718] = { spell = 1289062, kind = "healer", severity = 1, cast = 3.5, flags = 0 },
                [720] = { spell = 1288235, kind = "healer", severity = 1, cast = 4, flags = 0 },
            },
            health = {
                { at = 66, what = "phase_transition" },
                { at = 35, what = "phase_transition" },
            },
            machine = {
                start = "NONE",
                phases = {
                    P1 = {
                        rules = {
                            { time = 9, event = 689, sync = true },
                            { time = 39, event = 690, sync = true },
                            { time = 29, event = 691, sync = true },
                            { time = 5, event = 692, sync = true },
                            { time = 4, event = 689, sync = true },
                            { time = 29, event = 691, sync = true },
                            { time = 35, event = 690, sync = true },
                            { time = 25, event = 691, sync = true },
                            { time = 1, event = 692, sync = true },
                            { time = 45, event = 692, group = "2124_loop_45", order = 1 },
                            { time = 45, event = 689, group = "2124_loop_45", order = 2 },
                            { time = 45, event = 691, group = "2124_loop_45", order = 3 },
                            { time = 45, event = 690, group = "2124_loop_45", order = 4 },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 9, 39, 29, 5 },
                            tolerance = 0.1,
                            priority = 100,
                        },
                    },
                    P2 = {
                        rules = {
                            { time = 12, event = 691, sync = true },
                            { time = 5, event = 692, sync = true },
                            { time = 19, event = 692, group = "2124_loop_19", order = 1 },
                            { time = 19, event = 691, group = "2124_loop_19", order = 2 },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 12, 5 },
                            tolerance = 0.1,
                            priority = 110,
                        },
                    },
                },
            },
        },
        [2125] = {
            instance = "Temple of Sethraliss",
            boss = "Merektha",
            raid = false,
            mapID = 1877,
            order = 2,
            journalID = 2143,
            portrait = 2176739,
            abilities = {
                [701] = { spell = 264172, kind = "other", severity = 2, cast = 3, flags = 0 },
                [702] = { spell = 1290031, kind = "targeted", severity = 2, cast = 3, flags = 0 },
                [703] = { spell = 1289602, kind = "targeted", severity = 1, cast = 3, flags = 0 },
                [704] = { spell = 1289205, kind = "mechanic", severity = 1, cast = 3, flags = 0 },
                [705] = { spell = 1290797, kind = "tank", severity = 1, cast = 3, flags = 128, label = "TANK HIT" },
                [706] = { spell = 1293048, kind = "healer", severity = 1, cast = 4, flags = 256 },
                [730] = { spell = 1293154, kind = "other", severity = 1, flags = 0 },
            },
            rules = {
                { time = 13, event = 702, sync = true },
                { time = 36, event = 706, sync = true },
                { time = 5, event = 705, sync = true },
                { time = 25, event = 703, sync = true },
                { time = 44, event = 704, sync = true },
                { time = 49, event = 701, sync = true },
            },
        },
        [2126] = {
            instance = "Temple of Sethraliss",
            boss = "Galvazzt",
            raid = false,
            mapID = 1877,
            order = 3,
            journalID = 2144,
            portrait = 2176727,
            abilities = {
                [697] = { spell = 1290531, kind = "healer", severity = 0, cast = 3, flags = 0 },
                [698] = { spell = 1291618, kind = "mechanic", severity = 1, flags = 0 },
            },
            rules = {
                { time = 20, event = 697, sync = true },
                { time = 5, event = 698, sync = true },
                { time = 22, event = 698, group = "2126_loop_22", order = 1 },
                { time = 22, event = 697, group = "2126_loop_22", order = 2 },
            },
        },
        [2127] = {
            instance = "Temple of Sethraliss",
            boss = "Avatar of Sethraliss",
            raid = false,
            mapID = 1877,
            order = 4,
            journalID = 2145,
            portrait = 2176713,
            abilities = {
                [827] = { spell = 1301963, kind = "other", severity = 2, flags = 0 },
                [828] = { spell = 1301202, kind = "other", severity = 2, flags = 0 },
            },
            rules = {
                { time = 13, event = 92, sync = true },
                { time = 15, event = 828, sync = true },
            },
        },
        [2139] = {
            instance = "Kings' Rest",
            boss = "The Golden Serpent",
            raid = false,
            mapID = 1762,
            order = 1,
            journalID = 2165,
            portrait = 2176751,
            abilities = {
                [767] = { spell = 265773, kind = "targeted", severity = 1, cast = 2, flags = 0 },
                [891] = { spell = 265910, kind = "tank", severity = 1, cast = 1.5, flags = 128, label = "TANK HIT" },
                [892] = { spell = 1311987, kind = "healer", severity = 1, cast = 2, channel = 5, flags = 0 },
                [893] = { spell = 265923, kind = "mechanic", severity = 1, cast = 2, flags = 0 },
            },
            rules = {
                { time = 8, event = 891, sync = true },
                { time = 5, event = 767, sync = true },
                { time = 54, event = 893, sync = true },
                { time = 14, event = 892, sync = true },
                { time = 28, event = 892 },
                { time = 25, event = 767, group = "2139_loop_25", order = 1 },
                { time = 25, event = 891, group = "2139_loop_25", order = 2 },
            },
        },
        [2140] = {
            instance = "Kings' Rest",
            boss = "The Council of Tribes",
            raid = false,
            mapID = 1762,
            order = 3,
            journalID = 2170,
            portrait = 2176750,
            abilities = {
                [870] = { spell = 266206, kind = "other", severity = 1, cast = 2.8, flags = 0 },
                [871] = { spell = 266231, kind = "targeted", severity = 1, cast = 1.5, flags = 4 },
                [872] = { spell = 266951, kind = "mechanic", severity = 1, cast = 6, flags = 0 },
                [873] = { spell = 266237, kind = "tank", severity = 1, cast = 2, flags = 128, label = "TANK HIT" },
                [874] = { spell = 1305810, kind = "targeted", severity = 1, cast = 1, flags = 0 },
                [875] = { spell = 267273, kind = "mechanic", severity = 2, cast = 4, flags = 64 },
                [876] = { spell = 267060, kind = "mechanic", severity = 2, cast = 2.5, flags = 0 },
            },
            machine = {
                start = "NONE",
                phases = {
                    P1 = {
                        rules = {
                            { time = 8, event = 870, sync = true },
                            { time = 15, event = 871, sync = true },
                            { time = 14.75, event = 870 },
                            { time = 16.5, event = 871 },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 8, 15 },
                            tolerance = 0.1,
                            priority = 100,
                        },
                    },
                    P2 = {
                        rules = {
                            { time = 5, event = 872, sync = true },
                            { time = 14, event = 873, sync = true },
                            { time = 20, event = 872 },
                            { time = 22, event = 873 },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 5, 14 },
                            tolerance = 0.1,
                            priority = 110,
                        },
                    },
                    P3 = {
                        rules = {
                            { time = 2, event = 874, sync = true },
                            { time = 10, event = 875, sync = true },
                            { time = 20, event = 876, sync = true },
                            { time = 7, event = 874 },
                            { time = 24.4, event = 875 },
                            { time = 52.5, event = 876 },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 2, 10, 20 },
                            tolerance = 0.1,
                            priority = 120,
                        },
                    },
                },
            },
        },
        [2142] = {
            instance = "Kings' Rest",
            boss = "Mchimba the Embalmer",
            raid = false,
            mapID = 1762,
            order = 2,
            journalID = 2171,
            portrait = 2176738,
            abilities = {
                [878] = { spell = 267639, kind = "other", severity = 1, cast = 4, flags = 0 },
                [879] = { spell = 267702, kind = "mechanic", severity = 2, cast = 3, flags = 0 },
                [880] = { spell = 267618, kind = "targeted", severity = 1, cast = 2, channel = 6, flags = 256 },
                [973] = { spell = 1312146, kind = "other", severity = 1, cast = 3, flags = 0 },
            },
            rules = {
                { time = 20, event = 878, sync = true },
                { time = 60, event = 879, sync = true },
                { time = 5, event = 880, sync = true },
                { time = 30, event = 973, sync = true },
                { time = 32, event = 880 },
                { time = 30, event = 878 },
            },
        },
        [2143] = {
            instance = "Kings' Rest",
            boss = "King Dazar",
            raid = false,
            mapID = 1762,
            order = 4,
            journalID = 2172,
            portrait = 2176720,
            abilities = {
                [831] = { spell = 1303105, kind = "targeted", severity = 1, cast = 4, channel = 1.5, flags = 0 },
                [832] = { spell = 268586, kind = "tank", severity = 1, cast = 1.5, channel = 2.4, flags = 128, label = "TANK HIT" },
                [833] = { spell = 1303267, kind = "mechanic", severity = 1, cast = 6, flags = 0 },
                [834] = { spell = 269232, kind = "targeted", severity = 0, cast = 2, channel = 2, flags = 4 },
                [835] = { spell = 269369, kind = "other", severity = 2, cast = 4, flags = 0 },
                [836] = { spell = 1303327, kind = "healer", severity = 1, flags = 0 },
                [837] = { spell = 1303488, kind = "tank", severity = 1, cast = 2, flags = 128, label = "TANK HIT" },
            },
            health = {
                { at = 80, what = "phase_transition" },
            },
            rules = {
                { time = 23, event = 832, sync = true },
                { time = 30, event = 833, sync = true },
                { time = 15, event = 831, sync = true },
                { time = 8, event = 834, sync = true },
                { time = 14, event = 835, sync = true },
                { time = 10, event = 834, group = "2143_loop_10", order = 1 },
                { time = 10, event = 835, group = "2143_loop_10", order = 2 },
                { time = 36, event = 837, sync = true },
                { time = 9, event = 836, sync = true },
                { time = 38, event = 832, sync = true },
                { time = 24, event = 833, sync = true },
            },
            actions = {
                [831] = { finish = "timer", ignoreStateFor = 1 },
                [834] = { finish = "timer", ignoreStateFor = 1 },
            },
        },
        [2606] = {
            instance = "Ruby Life Pools",
            boss = "Kokia Blazehoof",
            raid = false,
            mapID = 2521,
            order = 2,
            journalID = 2485,
            portrait = 4741520,
            abilities = {
                [882] = { spell = 372863, kind = "healer", severity = 2, cast = 5, flags = 0 },
                [883] = { spell = 372107, kind = "mechanic", severity = 1, cast = 2.5, flags = 0 },
                [884] = { spell = 372858, kind = "tank", severity = 0, channel = 3, flags = 384, label = "TANK HIT" },
            },
            rules = {
                { time = 28, event = 884, sync = true },
                { time = 19, event = 883, sync = true },
                { time = 8, event = 882, sync = true },
                { time = 20, event = 883 },
                { time = 40, event = 882, group = "2606_loop_40", order = 1 },
                { time = 40, event = 884, group = "2606_loop_40", order = 2 },
            },
        },
        [2609] = {
            instance = "Ruby Life Pools",
            boss = "Melidrussa Chillworn",
            raid = false,
            mapID = 2521,
            order = 1,
            journalID = 2488,
            portrait = 4741523,
            abilities = {
                [866] = { spell = 396044, kind = "other", severity = 1, cast = 3, flags = 0 },
                [867] = { spell = 372851, kind = "healer", severity = 1, cast = 4.5, flags = 0 },
                [868] = { spell = 373680, kind = "mechanic", severity = 1, channel = 604800, flags = 0 },
                [869] = { spell = 373046, kind = "mechanic", severity = 2, cast = 4, flags = 0 },
            },
            health = {
                { at = 66, what = "phase_transition" },
                { at = 33, what = "phase_transition" },
            },
            rules = {
                { time = 5, event = 866, sync = true },
                { time = 15, event = 867, sync = true },
                { time = 12, event = 868 },
                { time = 24, event = 866, group = "2609_loop_27", order = 1 },
                { time = 24, event = 867, group = "2609_loop_27", order = 2 },
            },
        },
        [2623] = {
            instance = "Ruby Life Pools",
            boss = "Kyrakka and Erkhart Stormvein",
            raid = false,
            mapID = 2521,
            order = 3,
            journalID = 2503,
            portrait = 4867810,
            abilities = {
                [885] = { spell = 381516, kind = "mechanic", severity = 1, cast = 5, flags = 0 },
                [887] = { spell = 381517, kind = "mechanic", severity = 1, cast = 1.5, flags = 0 },
                [888] = { spell = 381512, kind = "tank", severity = 0, cast = 2.5, flags = 128, label = "TANK HIT" },
                [889] = { spell = 381602, kind = "targeted", severity = 1, cast = 2, flags = 0 },
                [890] = { spell = 381525, kind = "other", severity = 1, cast = 4, channel = 4, flags = 0 },
                [894] = { spell = 381605, kind = "targeted", severity = 1, cast = 2, flags = 0 },
            },
            rules = {
                { time = 10, event = 887, sync = true },
                { time = 21, event = 885, sync = true },
                { time = 5, event = 888, sync = true },
                { time = 1, event = 890, sync = true },
                { time = 12, event = 889, sync = true },
                { time = 22.5, event = 888 },
                { time = 21.5, event = 887 },
                { time = 25, event = 885 },
                { time = 9, event = 894 },
                { time = 20, event = 890, group = "2623_loop_20", order = 1 },
                { time = 20, event = 889, group = "2623_loop_20", order = 2 },
                { time = 16, event = 890, group = "2623_loop_16", order = 1 },
                { time = 16, event = 894, group = "2623_loop_16", order = 2 },
            },
        },
        [3101] = {
            instance = "Murder Row",
            boss = "Kystia Manaheart",
            raid = false,
            mapID = 2813,
            order = 0,
            journalID = 2679,
            portrait = 7372495,
            abilities = {
                [120] = { spell = 1264095, kind = "mechanic", severity = 1, flags = 0 },
                [122] = { spell = 1253811, kind = "other", severity = 2, cast = 3.5, channel = 5, flags = 0 },
                [202] = { spell = 1223906, kind = "other", severity = 1, cast = 3.5, flags = 0 },
                [610] = { spell = 1230304, kind = "mechanic", severity = 1, cast = 2, channel = 15, flags = 0 },
                [613] = { spell = 1248184, kind = "other", severity = 0, flags = 0 },
            },
            health = {
                { at = 20, what = "phase_transition" },
            },
            rules = {
                { time = 8, event = 122, sync = true },
                { time = 12, event = 202, sync = true },
                { time = 15, event = 120, sync = true },
                { time = 27.5, event = 122 },
                { time = 30, event = 120 },
                { time = 12, event = 202 },
            },
        },
        [3102] = {
            instance = "Murder Row",
            boss = "Zaen Bladesorrow",
            raid = false,
            mapID = 2813,
            order = 1,
            journalID = 2680,
            portrait = 7372516,
            abilities = {
                [123] = { spell = 1214357, kind = "targeted", severity = 1, flags = 0 },
                [124] = { spell = 474765, kind = "other", severity = 1, flags = 0 },
                [125] = { spell = 1218347, kind = "mechanic", severity = 1, channel = 6, flags = 5 },
                [127] = { spell = 474478, kind = "healer", severity = 0, channel = 3, flags = 0 },
                [193] = { spell = 1222795, kind = "tank", severity = 0, cast = 3, flags = 192, label = "TANK HIT" },
                [615] = { spell = 1218465, kind = "other", severity = 2, flags = 0 },
                [616] = { spell = 1218466, kind = "other", severity = 2, flags = 0 },
            },
            rules = {
                { time = 12, event = 124, sync = true },
                { time = 26, event = 193, sync = true },
                { time = 36, event = 125, sync = true },
                { time = 18, event = 123, sync = true },
                { time = 8, event = 127, sync = true },
                { time = 16, event = 124 },
            },
        },
        [3103] = {
            raid = false,
            mapID = 2813,
            order = 3,
            journalID = 2681,
            portrait = 7372515,
            abilities = {
                [30] = { spell = 473898, kind = "tank", severity = 1, cast = 3, flags = 0, label = "TANK HIT" },
                [32] = { spell = 474197, kind = "mechanic", severity = 2, cast = 4, flags = 0 },
                [559] = { spell = 1214641, kind = "targeted", severity = 1, cast = 3, flags = 0 },
                [752] = { spell = 1295453, kind = "healer", severity = 1, cast = 3, flags = 0, label = "AOE" },
            },
            rules = {
                { time = 6, event = 30, sync = true },
                { time = 15, event = 559, sync = true },
                { time = 35, event = 32, sync = true },
                { time = 30, event = 752, sync = true },
                { time = 27, event = 30 },
            },
        },
        [3105] = {
            instance = "Murder Row",
            boss = "Lithiel Cinderfury",
            raid = false,
            mapID = 2813,
            order = 4,
            journalID = 2682,
            portrait = 7372511,
            abilities = {
                [37] = { spell = 474462, kind = "healer", severity = 1, cast = 5, flags = 0 },
                [38] = { spell = 474408, kind = "mechanic", severity = 0, cast = 2, flags = 0 },
                [207] = { spell = 1217345, kind = "mechanic", severity = 1, cast = 10, flags = 1 },
            },
            rules = {
                { time = 15, event = 37, sync = true },
                { time = 10, event = 38, sync = true },
                { time = 24, event = 207, sync = true },
                { time = 57, event = 38 },
                { time = 55, event = 37 },
                { time = 59, event = 207 },
            },
        },
        [3199] = {
            instance = "The Blinding Vale",
            boss = "Lightblossom Trinity",
            raid = false,
            mapID = 2859,
            order = 1,
            journalID = 2769,
            portrait = 7478231,
            abilities = {
                [173] = { spell = 1234753, kind = "tank", severity = 0, cast = 3, flags = 128, label = "TANK HIT" },
                [174] = { spell = 1234850, kind = "mechanic", severity = 0, cast = 2.5, flags = 0 },
                [175] = { spell = 1235640, kind = "targeted", severity = 0, cast = 1.5, flags = 4 },
                [176] = { spell = 1235640, kind = "targeted", severity = 0, cast = 1.5, flags = 4 },
                [177] = { spell = 1235564, kind = "mechanic", severity = 2, cast = 3, channel = 8, flags = 0 },
            },
            machine = {
                start = "MAIN",
                phases = {
                    MAIN = {
                        rules = {
                            { time = 8, event = 176, sync = true },
                            { time = 5, event = 173, sync = true },
                            { time = 35, event = 177, sync = true },
                            { time = 20, event = 174, sync = true },
                            { time = 45, event = 173, group = "3199_loop_45", order = 1 },
                            { time = 45, event = 176, group = "3199_loop_45", order = 2 },
                            { time = 45, event = 174, group = "3199_loop_45", order = 3 },
                            { time = 45, event = 177, group = "3199_loop_45", order = 4 },
                        },
                        normalize = {
                            { min = 41, max = 45, snap = 45 },
                        },
                    },
                },
            },
            actions = {
                [176] = { finish = "timer" },
            },
        },
        [3200] = {
            instance = "The Blinding Vale",
            boss = "Ikuzz the Light Hunter",
            raid = false,
            mapID = 2859,
            order = 2,
            journalID = 2770,
            portrait = 7478232,
            abilities = {
                [178] = { spell = 1236746, kind = "healer", severity = 1, cast = 3, flags = 0 },
                [179] = { spell = 1236709, kind = "healer", severity = 1, cast = 2, channel = 6, flags = 256 },
                [180] = { spell = 1253410, kind = "special", severity = 2, cast = 4, flags = 0 },
                [1001] = { spell = 1237073, kind = "other", severity = 1, cast = 1, flags = 0 },
            },
            rules = {
                { time = 6, event = 178, sync = true },
                { time = 22, event = 179, sync = true },
                { time = 50, event = 180, sync = true },
                { time = 29, event = 178 },
            },
        },
        [3201] = {
            instance = "The Blinding Vale",
            boss = "Lightwarden Ruia",
            raid = false,
            mapID = 2859,
            order = 3,
            journalID = 2771,
            portrait = 7478233,
            abilities = {
                [181] = { spell = 1239824, kind = "mechanic", severity = 1, cast = 2, flags = 256 },
                [182] = { spell = 1240098, kind = "other", severity = 1, flags = 0 },
                [183] = { spell = 1240210, kind = "other", severity = 1, cast = 2.5, flags = 0 },
                [184] = { spell = 1241058, kind = "healer", severity = 1, cast = 2, flags = 4 },
                [185] = { spell = 1239885, kind = "mechanic", severity = 1, cast = 2, flags = 0 },
                [186] = { spell = 1239882, kind = "mechanic", severity = 1, cast = 2, flags = 0 },
                [187] = { spell = 1239883, kind = "mechanic", severity = 1, cast = 2, flags = 0 },
                [188] = { spell = 1241067, kind = "mechanic", severity = 2, cast = 4, channel = 604800, flags = 0 },
                [780] = { spell = 1296871, kind = "healer", severity = 0, flags = 0, label = "AOE" },
            },
            health = {
                { at = 70, what = "phase_transition" },
                { at = 40, what = "phase_transition" },
            },
            machine = {
                start = "NONE",
                phases = {
                    P1 = {
                        rules = {
                            { time = 0.5, event = 186, sync = true },
                            { time = 5, event = 181, sync = true },
                            { time = 18, event = 182, sync = true },
                            { time = 20, event = 181, group = "3201_P1_loop_20", order = 1 },
                            { time = 20, event = 182, group = "3201_P1_loop_20", order = 2 },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 0.5, 5, 18 },
                            tolerance = 0.1,
                            priority = 100,
                        },
                        normalize = {
                            { min = 20, max = 21, snap = 20 },
                        },
                    },
                    P2 = {
                        rules = {
                            { time = 3, event = 184, sync = true },
                            { time = 9, event = 183, sync = true },
                            { time = 20, event = 184, group = "3201_P2_loop_20", order = 1 },
                            { time = 20, event = 183, group = "3201_P2_loop_20", order = 2 },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 3, 9 },
                            tolerance = 0.1,
                            priority = 110,
                        },
                        normalize = {
                            { min = 20, max = 21, snap = 20 },
                        },
                    },
                    P3 = {
                        rules = {
                            { time = 2.5, event = 188 },
                            { time = 7.3, event = 181, sync = true },
                            { time = 15.3, event = 184, sync = true },
                            { time = 23.3, event = 182, sync = true },
                            { time = 31.1, event = 183, sync = true },
                            { time = 32, event = 181, group = "3201_loop_32", order = 1 },
                            { time = 32, event = 184, group = "3201_loop_32", order = 2 },
                            { time = 32, event = 182, group = "3201_loop_32", order = 3 },
                            { time = 32, event = 183, group = "3201_loop_32", order = 4 },
                        },
                        enter = { mode = "duration_once", time = 2.5, tolerance = 0.1, priority = 120 },
                        normalize = {
                            { min = 31.5, max = 32.5, snap = 32 },
                        },
                    },
                },
            },
        },
        [3202] = {
            instance = "The Blinding Vale",
            boss = "Ziekett",
            raid = false,
            mapID = 2859,
            order = 4,
            journalID = 2772,
            portrait = 7478234,
            abilities = {
                [189] = { spell = 1246372, kind = "mechanic", severity = 1, cast = 3, flags = 0 },
                [190] = { spell = 1247685, kind = "tank", severity = 0, cast = 3, flags = 132, label = "TANK HIT" },
                [191] = { spell = 1246607, kind = "targeted", severity = 2, cast = 5, flags = 0 },
                [192] = { spell = 1246858, kind = "healer", severity = 1, cast = 2, flags = 0 },
            },
            rules = {
                { time = 26, event = 190, sync = true },
                { time = 4, event = 189, sync = true },
                { time = 40, event = 191, sync = true },
                { time = 14, event = 192, sync = true },
                { time = 50, event = 189, group = "3202_loop_50", order = 1 },
                { time = 50, event = 192, group = "3202_loop_50", order = 2 },
                { time = 50, event = 190, group = "3202_loop_50", order = 3 },
                { time = 50, event = 191, group = "3202_loop_50", order = 4 },
            },
        },
        [3207] = {
            instance = "Den of Nalorakk",
            boss = "The Hoardmonger",
            raid = false,
            mapID = 2825,
            order = 1,
            journalID = 2776,
            portrait = 7455022,
            abilities = {
                [86] = { spell = 1234233, kind = "healer", severity = 2, channel = 7, flags = 0 },
                [87] = { spell = 1234021, kind = "other", severity = 1, cast = 4, flags = 0 },
                [88] = { spell = 1234681, kind = "healer", severity = 0, cast = 3, flags = 256 },
            },
            health = {
                { at = 90, what = "phase_transition" },
                { at = 70, what = "phase_transition" },
                { at = 40, what = "phase_transition" },
            },
            rules = {
                { time = 30, event = 86, sync = true },
                { time = 6, event = 88, sync = true },
                { time = 16, event = 87, sync = true },
            },
        },
        [3208] = {
            instance = "Den of Nalorakk",
            boss = "Sentinel of Winter",
            raid = false,
            mapID = 2825,
            order = 2,
            journalID = 2777,
            portrait = 7455021,
            abilities = {
                [67] = { spell = 1235548, kind = "targeted", severity = 0, cast = 1, flags = 8 },
                [68] = { spell = 1235623, kind = "other", severity = 1, cast = 3, flags = 0 },
                [69] = { spell = 1235783, kind = "mechanic", severity = 1, cast = 3, flags = 0 },
                [70] = { spell = 1235656, kind = "healer", severity = 2, cast = 4, channel = 8, flags = 256 },
            },
            rules = {
                { time = 7, event = 67, sync = true },
                { time = 13, event = 68, sync = true },
                { time = 25, event = 69, sync = true },
                { time = 50, event = 70, sync = true },
            },
        },
        [3209] = {
            instance = "Den of Nalorakk",
            boss = "Nalorakk",
            raid = false,
            mapID = 2825,
            order = 3,
            journalID = 2778,
            portrait = 7455020,
            abilities = {
                [89] = { spell = 1255385, kind = "other", severity = 0, cast = 2, flags = 256 },
                [90] = { spell = 1242860, kind = "targeted", severity = 1, cast = 4, flags = 0 },
                [91] = { spell = 1243273, kind = "mechanic", severity = 2, channel = 1, flags = 0 },
                [92] = { spell = 1297792, kind = "mechanic", severity = 1, cast = 7, channel = 3, flags = 0 },
                [163] = { spell = 1262846, kind = "other", severity = 1, flags = 0 },
                [909] = { spell = 1242860, kind = "targeted", severity = 1, cast = 4, flags = 0 },
                [910] = { spell = 1243273, kind = "mechanic", severity = 2, channel = 1, flags = 0 },
                [911] = { spell = 1242860, kind = "targeted", severity = 1, cast = 4, flags = 0 },
            },
            rules = {
                { time = 13, event = 92, sync = true },
                { time = 5, event = 911, sync = true },
                { time = 54, event = 910, sync = true },
                { time = 25, event = 911, group = "3209_loop_25", order = 1 },
                { time = 25, event = 92, group = "3209_loop_25", order = 2 },
            },
        },
        [3285] = {
            instance = "Voidscar Arena",
            boss = "Taz'Rah",
            raid = false,
            mapID = 2923,
            order = 1,
            journalID = 2791,
            portrait = 7372577,
            abilities = {
                [39] = { spell = 1297017, kind = "tank", severity = 0, cast = 2, flags = 0, label = "TANK HIT" },
                [40] = { spell = 1262901, kind = "other", severity = 1, flags = 0 },
                [41] = { spell = 1300259, kind = "other", severity = 2, cast = 4, flags = 0 },
                [42] = { spell = 1225011, kind = "mechanic", severity = 2, flags = 1 },
                [558] = { spell = 1222098, kind = "mechanic", severity = 0, channel = 7.1, flags = 0 },
                [782] = { spell = 1296963, kind = "other", severity = 1, cast = 4, flags = 0 },
            },
            rules = {
                { time = 31, event = 41, sync = true },
                { time = 16, event = 782, sync = true },
                { time = 25, event = 39, sync = true },
                { time = 6, event = 558, sync = true },
            },
            actions = {
                [558] = { finish = "timer", ignoreStateFor = 1 },
            },
        },
        [3286] = {
            instance = "Voidscar Arena",
            boss = "Atroxus",
            raid = false,
            mapID = 2923,
            order = 2,
            journalID = 2792,
            portrait = 7372482,
            abilities = {
                [46] = { spell = 1222371, kind = "mechanic", severity = 1, flags = 0 },
                [47] = { spell = 1222642, kind = "tank", severity = 1, cast = 2, flags = 128, label = "TANK HIT" },
                [54] = { spell = 1222721, kind = "other", severity = 2, cast = 4, channel = 2, flags = 64 },
                [55] = { spell = 1226120, kind = "healer", severity = 1, channel = 3, flags = 64 },
                [297] = { spell = 1262497, kind = "healer", severity = 0, cast = 3, flags = 0 },
            },
            rules = {
                { time = 10, event = 47, sync = true },
                { time = 5, event = 55, sync = true },
                { time = 35, event = 297, sync = true },
                { time = 15, event = 54, sync = true },
                { time = 20, event = 55, group = "3286_loop_20", order = 1 },
                { time = 20, event = 47, group = "3286_loop_20", order = 2 },
                { time = 30, event = 54 },
            },
        },
        [3287] = {
            instance = "Voidscar Arena",
            boss = "Charonus",
            raid = false,
            mapID = 2923,
            order = 3,
            journalID = 2793,
            portrait = 7372489,
            abilities = {
                [56] = { spell = 1248112, kind = "mechanic", severity = 1, cast = 6, flags = 0 },
                [57] = { spell = 1227197, kind = "healer", severity = 1, cast = 4.8, flags = 0 },
                [58] = { spell = 1310025, kind = "mechanic", severity = 2, cast = 4, flags = 0 },
                [171] = { spell = 1227247, kind = "other", severity = 2, cast = 6, channel = 3, flags = 1 },
                [961] = { spell = 1311923, kind = "tank", severity = 1, cast = 5, flags = 128, label = "TANK HIT" },
            },
            rules = {
                { time = 5, event = 56, sync = true },
                { time = 43, event = 171, sync = true },
                { time = 17, event = 57, sync = true },
                { time = 34, event = 961, sync = true },
                { time = 28, event = 58, sync = true },
            },
        },
        [3379] = {
            raid = true,
            mapID = 2987,
            order = 0,
            journalID = 2849,
            portrait = 7966630,
            abilities = {
                [366] = { spell = 1268562, kind = "other", severity = 0, flags = 128 },
                [367] = { spell = 1257717, kind = "other", severity = 2, flags = 0 },
                [368] = { spell = 1257608, kind = "other", severity = 1, flags = 0 },
                [369] = { spell = 1258668, kind = "other", severity = 2, flags = 0 },
                [370] = { spell = 1260837, kind = "other", severity = 0, cast = 2, channel = 4, flags = 256 },
                [371] = { spell = 1273013, kind = "other", severity = 1, flags = 0 },
                [372] = { spell = 1276710, kind = "other", severity = 2, flags = 0 },
                [976] = { spell = 1313393, kind = "other", severity = 1, cast = 2, flags = 0 },
                [977] = { spell = 1257717, kind = "other", severity = 2, flags = 0 },
            },
        },
        [3420] = {
            raid = true,
            mapID = 3004,
            order = 5,
            journalID = 2871,
            portrait = 7966627,
            abilities = {
                [652] = { spell = 1285425, kind = "other", severity = 1, flags = 0 },
                [653] = { spell = 1305959, kind = "other", severity = 2, channel = 4, flags = 0 },
                [664] = { spell = 1277025, kind = "other", severity = 1, flags = 0 },
                [665] = { spell = 1285732, kind = "other", severity = 2, flags = 0 },
                [851] = { spell = 1296310, kind = "other", severity = 0, cast = 1.5, flags = 0 },
                [863] = { spell = 1296898, kind = "other", severity = 2, flags = 1 },
            },
        },
        [3421] = {
            raid = true,
            mapID = 3004,
            order = 6,
            journalID = 2887,
            portrait = 7966633,
            abilities = {
                [711] = { spell = 1289192, kind = "other", severity = 1, cast = 1, channel = 5, flags = 128 },
                [739] = { spell = 1288484, kind = "other", severity = 1, flags = 128 },
                [740] = { spell = 1294293, kind = "other", severity = 2, cast = 4, channel = 14, flags = 0 },
                [741] = { spell = 1294921, kind = "other", severity = 2, cast = 3, channel = 18, flags = 0 },
                [742] = { spell = 1290956, kind = "other", severity = 1, channel = 6, flags = 0 },
                [743] = { spell = 1290809, kind = "other", severity = 1, cast = 3, flags = 0 },
                [744] = { spell = 1291404, kind = "other", severity = 1, cast = 3, flags = 0 },
                [751] = { spell = 1290516, kind = "other", severity = 2, cast = 4.2, channel = 3.5, flags = 0 },
                [753] = { spell = 1291478, kind = "other", severity = 1, cast = 5, flags = 0 },
                [896] = { spell = 1303230, kind = "other", severity = 1, cast = 1, channel = 5, flags = 128 },
                [897] = { spell = 1306872, kind = "other", severity = 2, channel = 18, flags = 0 },
                [900] = { spell = 1308356, kind = "other", severity = 1, cast = 3, flags = 0 },
                [995] = { spell = 1308556, kind = "other", severity = 2, flags = 0 },
            },
        },
        [3429] = {
            raid = true,
            mapID = 3004,
            order = 7,
            journalID = 2883,
            portrait = 7966637,
            abilities = {
                [667] = { spell = 1285911, kind = "other", severity = 1, channel = 604800, flags = 0 },
                [669] = { spell = 1287227, kind = "other", severity = 1, flags = 0 },
                [677] = { spell = 1282487, kind = "other", severity = 1, channel = 8, flags = 384 },
                [678] = { spell = 1283485, kind = "other", severity = 1, flags = 256 },
                [679] = { spell = 1282281, kind = "other", severity = 0, flags = 0 },
                [680] = { spell = 1283832, kind = "other", severity = 0, cast = 2, flags = 0 },
                [681] = { spell = 1287200, kind = "other", severity = 1, flags = 0 },
                [682] = { spell = 1286918, kind = "other", severity = 2, cast = 15, flags = 769 },
                [683] = { spell = 1286308, kind = "other", severity = 0, flags = 0 },
                [684] = { spell = 1310882, kind = "other", severity = 0, cast = 2, flags = 0 },
                [685] = { spell = 1289900, kind = "other", severity = 1, flags = 512 },
                [686] = { spell = 1286573, kind = "other", severity = 1, channel = 4.5, flags = 0 },
                [687] = { spell = 1286441, kind = "other", severity = 1, channel = 3, flags = 512 },
                [794] = { spell = 1298381, kind = "other", severity = 1, channel = 8, flags = 384 },
                [803] = { spell = 1299266, kind = "other", severity = 1, flags = 0 },
                [811] = { spell = 1299680, kind = "other", severity = 1, channel = 3.5, flags = 0 },
                [812] = { spell = 1299960, kind = "other", severity = 1, flags = 0 },
                [898] = { spell = 1307279, kind = "other", severity = 1, channel = 3.5, flags = 0 },
            },
        },
        [3445] = {
            raid = true,
            mapID = 3004,
            order = 2,
            journalID = 2874,
            portrait = 7966628,
            abilities = {
                [637] = { spell = 1284251, kind = "other", severity = 1, cast = 1.5, flags = 0 },
                [638] = { spell = 1284434, kind = "other", severity = 1, cast = 2, flags = 0 },
                [639] = { spell = 1284458, kind = "other", severity = 1, cast = 1.5, flags = 128 },
                [640] = { spell = 1284487, kind = "other", severity = 1, cast = 1.5, flags = 128 },
                [641] = { spell = 1284483, kind = "other", severity = 1, cast = 2, flags = 8 },
                [642] = { spell = 1284485, kind = "other", severity = 1, cast = 1, flags = 0 },
                [643] = { spell = 1284588, kind = "other", severity = 2, channel = 30, flags = 1 },
                [668] = { spell = 26662, kind = "other", severity = 2, flags = 1 },
                [673] = { spell = 1288232, kind = "other", severity = 1, cast = 1, flags = 0 },
                [788] = { spell = 1296878, kind = "other", severity = 2, cast = 4, flags = 1 },
            },
        },
        [3455] = {
            raid = true,
            mapID = 3004,
            order = 4,
            journalID = 2882,
            portrait = 7966626,
            abilities = {
                [754] = { spell = 1280935, kind = "other", severity = 0, cast = 2, flags = 128 },
            },
        },
        [3456] = {
            instance = "Altar of Fangs",
            boss = "Rav'i",
            raid = false,
            mapID = 2993,
            order = 1,
            journalID = 2878,
            portrait = 7966629,
            abilities = {
                [795] = { spell = 1298223, kind = "mechanic", severity = 2, channel = 60, flags = 0 },
                [796] = { spell = 1296219, kind = "other", severity = 1, cast = 3, flags = 0 },
                [797] = { spell = 1296220, kind = "healer", severity = 0, cast = 2, flags = 0 },
                [798] = { spell = 1296058, kind = "other", severity = 0, cast = 3, flags = 0 },
                [899] = { spell = 1307894, kind = "mechanic", severity = 1, cast = 3, flags = 0 },
                [901] = { spell = 1307921, kind = "mechanic", severity = 1, flags = 0 },
                [902] = { spell = 1307768, kind = "other", severity = 2, channel = 60, flags = 0 },
            },
            rules = {
                { time = 8, event = 797, sync = true },
                { time = 25, event = 795, sync = true },
                { time = 13, event = 798, sync = true },
                { time = 45, event = 795, sync = true },
                { time = 23, event = 899, sync = true },
                { time = 24, event = 797 },
            },
            actions = {
                [795] = { finish = "timer", ignoreStateFor = 1 },
            },
        },
        [3457] = {
            instance = "Altar of Fangs",
            boss = "The Writhing Coil",
            raid = false,
            mapID = 2993,
            order = 2,
            journalID = 2879,
            portrait = 7966635,
            abilities = {
                [813] = { spell = 1299154, kind = "healer", severity = 0, cast = 2, flags = 0 },
                [814] = { spell = 1298949, kind = "tank", severity = 0, cast = 3, flags = 0, label = "TANK HIT" },
                [815] = { spell = 1299130, kind = "other", severity = 0, cast = 3, flags = 0 },
                [816] = { spell = 1299053, kind = "mechanic", severity = 2, cast = 5, channel = 60, flags = 0 },
                [817] = { spell = 1300503, kind = "mechanic", severity = 0, channel = 20, flags = 0 },
                [818] = { spell = 1300686, kind = "mechanic", severity = 1, flags = 0 },
                [938] = { spell = 1310357, kind = "other", severity = 1, flags = 0 },
                [939] = { spell = 1310547, kind = "other", severity = 1, flags = 0 },
            },
            machine = {
                start = "NONE",
                phases = {
                    P1 = {
                        rules = {
                            { time = 1, event = 813, sync = true },
                            { time = 7, event = 814, sync = true },
                            { time = 44, event = 816, sync = true },
                            { time = 14, event = 938, sync = true },
                            { time = 30, event = 815, sync = true },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 1, 7, 44, 14, 30 },
                            tolerance = 0.1,
                            priority = 100,
                        },
                    },
                    P2 = {
                        rules = {
                            { time = 10, event = 939, sync = true },
                            { time = 25, event = 818, sync = true },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 10, 25 },
                            tolerance = 0.1,
                            priority = 110,
                        },
                    },
                    P3 = {
                        rules = {
                            { time = 10, event = 813, sync = true },
                            { time = 53, event = 816, sync = true },
                            { time = 23, event = 938, sync = true },
                            { time = 16, event = 814, sync = true },
                            { time = 39, event = 815, sync = true },
                        },
                        enter = {
                            mode = "sync_batch_all",
                            times = { 10, 53, 23, 16, 39 },
                            tolerance = 0.1,
                            priority = 120,
                        },
                    },
                },
            },
        },
        [3458] = {
            instance = "Altar of Fangs",
            boss = "Zul'jan",
            raid = false,
            mapID = 2993,
            order = 3,
            journalID = 2880,
            portrait = 7966636,
            abilities = {
                [821] = { spell = 1301413, kind = "targeted", severity = 1, cast = 5, flags = 0 },
                [822] = { spell = 1300876, kind = "mechanic", severity = 2, cast = 4, channel = 8, flags = 0, label = "AOE" },
                [823] = { spell = 1301111, kind = "mechanic", severity = 1, cast = 3, channel = 6, flags = 0 },
                [824] = { spell = 1301350, kind = "tank", severity = 0, cast = 1.5, channel = 0.5, flags = 128, label = "TANK HIT" },
            },
            rules = {
                { time = 32, event = 821, sync = true },
                { time = 14, event = 823, sync = true },
                { time = 26, event = 824, sync = true },
                { time = 26, event = 824, sync = true },
                { time = 64, event = 822 },
                { time = 30, event = 824 },
                { time = 14, event = 821 },
            },
            actions = {
                [822] = { finish = "timer", ignoreStateFor = 1 },
            },
        },
        [3470] = {
            raid = true,
            mapID = 3004,
            order = 1,
            journalID = 2888,
            portrait = 7966631,
            abilities = {
                [675] = { spell = 1287426, kind = "other", severity = 1, flags = 0 },
                [676] = { spell = 1285681, kind = "other", severity = 2, channel = 4, flags = 0 },
                [693] = { spell = 1293497, kind = "other", severity = 0, flags = 0 },
                [694] = { spell = 1289923, kind = "other", severity = 2, cast = 2, flags = 0 },
                [695] = { spell = 1295397, kind = "other", severity = 2, flags = 0 },
                [696] = { spell = 1290679, kind = "other", severity = 1, cast = 2, flags = 0 },
                [710] = { spell = 1292036, kind = "other", severity = 1, flags = 128 },
                [712] = { spell = 1290001, kind = "other", severity = 1, flags = 0 },
                [731] = { spell = 1293212, kind = "other", severity = 0, flags = 0 },
                [804] = { spell = 1299673, kind = "other", severity = 2, cast = 5, flags = 0 },
                [865] = { spell = 1305421, kind = "other", severity = 1, flags = 0 },
                [877] = { spell = 1305993, kind = "other", severity = 0, flags = 0 },
            },
        },
        [3492] = {
            raid = true,
            mapID = 3004,
            order = 8,
            journalID = 2895,
            portrait = 7966634,
            abilities = {
                [699] = { spell = 1298367, kind = "other", severity = 2, cast = 5, channel = 3, flags = 128 },
                [700] = { spell = 1286860, kind = "other", severity = 2, cast = 6.5, channel = 20, flags = 512 },
                [719] = { spell = 1292188, kind = "other", severity = 2, flags = 1 },
                [746] = { spell = 1286905, kind = "other", severity = 2, cast = 1.6, flags = 0 },
                [799] = { spell = 1298559, kind = "other", severity = 2, flags = 128 },
                [800] = { spell = 1295905, kind = "other", severity = 1, cast = 5, flags = 0 },
                [806] = { spell = 1299757, kind = "other", severity = 1, flags = 128 },
                [807] = { spell = 1300530, kind = "other", severity = 1, flags = 0 },
                [810] = { spell = 1286905, kind = "other", severity = 2, cast = 1.6, flags = 0 },
                [825] = { spell = 1300751, kind = "other", severity = 1, cast = 4, flags = 0 },
                [826] = { spell = 1301510, kind = "other", severity = 2, flags = 1 },
                [830] = { spell = 1302982, kind = "other", severity = 1, flags = 0 },
                [847] = { spell = 1304527, kind = "other", severity = 2, flags = 128 },
                [912] = { spell = 1296301, kind = "other", severity = 1, cast = 4, flags = 0 },
                [949] = { spell = 1292999, kind = "other", severity = 0, flags = 0 },
                [950] = { spell = 1299757, kind = "other", severity = 1, flags = 128 },
                [952] = { spell = 1311037, kind = "other", severity = 2, cast = 2.5, channel = 3, flags = 128 },
                [975] = { spell = 1287265, kind = "other", severity = 1, flags = 0 },
            },
        },
        [3497] = {
            raid = true,
            mapID = 3004,
            order = 3,
            journalID = 2894,
            portrait = 7966632,
            abilities = {
                [721] = { spell = 1291390, kind = "other", severity = 2, cast = 7, flags = 0 },
                [722] = { spell = 1286921, kind = "other", severity = 0, flags = 0 },
                [723] = { spell = 1296025, kind = "other", severity = 1, flags = 0 },
                [724] = { spell = 1290742, kind = "other", severity = 0, cast = 9, flags = 0 },
                [725] = { spell = 1296092, kind = "other", severity = 1, flags = 0 },
                [726] = { spell = 1296061, kind = "other", severity = 0, flags = 0 },
                [727] = { spell = 1291933, kind = "other", severity = 0, cast = 3, flags = 0 },
                [728] = { spell = 1295817, kind = "other", severity = 2, flags = 0 },
                [729] = { spell = 1292104, kind = "other", severity = 2, cast = 7, flags = 0 },
                [737] = { spell = 1290740, kind = "other", severity = 0, cast = 9, flags = 0 },
                [738] = { spell = 1290743, kind = "other", severity = 0, cast = 9, flags = 0 },
                [768] = { spell = 1295854, kind = "other", severity = 1, channel = 3.5, flags = 0 },
                [776] = { spell = 1295886, kind = "other", severity = 1, flags = 0 },
                [777] = { spell = 1295935, kind = "other", severity = 1, flags = 0 },
                [781] = { spell = 1297625, kind = "other", severity = 2, flags = 0 },
                [783] = { spell = 1292779, kind = "other", severity = 2, cast = 5, channel = 3600, flags = 0 },
            },
        },
    },
}
